### PR TITLE
README.md modified from ggpark

### PR DESCRIPTION
**Pull request by ggpark1218**
I added contents about OSS class. Check please!

### CODE REVIEW

**Comment by SeoYeonJu4382** [comment]
and can you write your student id?

**Comment by ggpark1218** [comment]
okay, I'll try!

**Comment by ggpark1218** [comment]
Thank you :)

**Comment by ggpark1218** [comment]
Is it okay?

**Comment by ghost** [comment]
thank you! please leave a date below your id!

**Pull request merged**
